[package]
name = "procedural"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "*"
syn = "2.0"
quote = "1.0"
derive-syn-parse = "0.1.5"
convert_case = "0.6.0"
colored = "2.0.0"

[features]
left = []
right = []
